### ISSUE TITLE
Feature request: optional forced iri update

### ISSUE THREAD

**Issue by ghost** [SemkoDev/nelson.cli#27]
Hello,

First: I've had a long and productive talk with h3n. He helped to see things more clearly. Thx.

My problem with the network: There are now several versions in the wild. The most recent is 1.4.1.4. But as hugh network it should stay as monolithic as possible. So older versions should deprecate over time and defunced.

I propose that every nelson installation should be able to learn about new versions automatically. If there is a confirmed new version found then the local node is forced to update (optional but default: on) the IRI at a random point within lets say 30 days. After that plus a grace time the local nelson can discard older nodes because there virtually none.
If you need to install an old version for what ever reason then just switch off this option.

Positive:
- One network, one version
- ~30 days to revoke a version
- all nodes have 99.995% uptime within the update time (asuming 30 seconds restart time within these 30 days)
- network downtime closest to 0%
- new versions only need to know how to talk to version minus 1
- option is optional :)
- nelsons learn about the version distribution in the network

Negative:
- single outdated nodes are bound to their one small world (micro netsplit)

... and no, hardware nodes a unlikely full nodes. So there is no point here.

This can work.
Please discuss it before you close it.

Michael

**Comment by snowlove** [comment]
IMO the Default should be Off, where the end user accepts the liability of enabling this options rather than having it forced on them if they skip over it. situations could arise where say the main repo is compromised someone pushes a malicious update, nelson automatically grabs the update. now we have  rogue nodes that will start propagating through the network as nelson updates, until breach is fixed, and may linger for sometime if the operator doesn't notice and is taking a hands off approach

**Comment by nuriel77** [comment]
I also think that auto-updating versions at this stage is risky. Although the last 1.4.1.4 simply required replacing the jar file, the upgrade before that required to restart IRI with `--rescan` option due to database scheme updates. It might be the case in the future that an update requires some manual action depending on the instructions provided by IOTA devs.

**Comment by romansemko** [comment]
I think there should be a certain separation of concerns. Nelson just manages the neighborhood. It is not an update manager for IRI. While some kind of automatic IRI updates might be useful, they can also be risky, as suggested above. It has to be discussed outside of the Nelson scope, IMHO.

Thanks for the suggestion, though!
